fix(scb-bot): Adds error handling to remote version fetching
Refactors the version fectching from github releases to fail on
connectivity issues and stop the workflow from continuing

Comments are also added to make it more clear how the workflow runs

Signed-off-by: Ilyes Ben Dlala <ilyes.bendlala@iteratec.com>

diff --git a/.github/workflows/scb-bot.yaml b/.github/workflows/scb-bot.yaml
--- a/.github/workflows/scb-bot.yaml
+++ b/.github/workflows/scb-bot.yaml
@@ -1,3 +1,12 @@
+# This is a Github Action workflow that runs daily at 9:15 AM UTC Time. 
+# It checks if any of the scanners listed in the matrix section are outdated. 
+# If a scanner is outdated, it checks if a pull request to upgrade that scanner already exists.
+# If it does not, it creates a new pull request with a title that includes the current and new versions of the scanner. 
+# It also includes the changelog for the new version of the scanner in the body of the pull request.
+# This workflow uses a number of third-party actions to accomplish these tasks, 
+# including mikefarah/yq to fetch local and remote versions of the scanners,
+# crazy-max/ghaction-import-gpg to import a GPG key, and jq to parse the JSON output of the scanner version API.
+
 name: Check outdated scanners
 on:
   schedule:
@@ -39,35 +48,56 @@ jobs:
           git-user-signingkey: true
           git-commit-gpgsign: true
 
+      # Fetching scanner version from local chart .appVersion attribute
+      # this would look like 1.1.1 or v1.1.1 depending on the corresponding Docker image tag
       - name: Fetch local scanner version
         uses: mikefarah/yq@v4.4.1
         with:
           cmd: echo local=$(yq e .appVersion scanners/${{ matrix.scanner }}/Chart.yaml) >> $GITHUB_ENV
 
+      # Fetching scanner version API from local chart .annotations.versionApi attribute
+      # This would look like https://api.github.com/repos/OWASP/Amass/releases/latest
       - name: Fetch scanner's version API
         uses: mikefarah/yq@v4.4.1
         with:
           cmd: echo versionApi=$(yq e .annotations.versionApi scanners/${{ matrix.scanner }}/Chart.yaml) >> $GITHUB_ENV
 
+      # A hacky way to solve the problem where the docker image is in the "1.0" format and the github release is in the "v1.0" format
+      # We make sure to add or remove the "v" character when necessary
+      # example: local=1.0.0, release=v1.0.1, upgrade=1.0.1
       - name: Fetch latest release scanner version
-        # A hacky way to solve the problem where the docker image is in the "1.0" format and the github release is in the "v1.0" format
-        # We make sure to add or remove the "v" character when necessary
         run: |
-          local=${{env.local}}
-          release=$(curl -sL ${{env.versionApi}}  | jq -r ".tag_name" )
-          upgrade=$release
+            # Set the -e and -o pipefail options to cause the script to exit immediately
+            # if any command returns a non-zero exit status
+            set -e
+            set -o pipefail
 
-          if [[ ${local:0:1} != ${release:0:1} ]] ; then
-            if [[ ${local:0:1} == "v" ]] ; then
-              upgrade=v${release};
-            elif [[ ${release:0:1} == "v" ]] ; then
-              upgrade=$(echo $release| tr -d "v")
+            local=${{env.local}}
+            release=$(curl -sL ${{env.versionApi}}  | jq -er ".tag_name" ) 
+            upgrade=$release
+
+            # Check the exit status of the curl and jq command
+            if [[ $? -ne 0 ]] ; then
+              echo "Error: Failed to download release version"
+              exit 1
             fi
-          fi
 
-          echo releaseGithub=$release >> $GITHUB_ENV #
-          echo release=$upgrade >> $GITHUB_ENV
-        # ^ The first echo sets how the release version looks in github releases and the second sets how the release version looks in docker images
+            # Check if the local and release versions are different
+            if [[ ${local:0:1} != ${release:0:1} ]] ; then
+              # Remove the "v" character from the local and release versions, if it exists
+              local=${local//v/}
+              release=${release//v/}
+
+              # Set the upgrade variable to the release version with a "v" prefix
+              upgrade=v$release
+            fi
+
+            # Save how the latest release version looks in github releases to an environment variable
+            echo releaseGithub=$release >> $GITHUB_ENV
+            # Save how the latest release version looks in docker images to an environment variable
+            echo release=$upgrade >> $GITHUB_ENV
+            # Output bash exit code
+            echo exitCode=$?
 
       - name: Check if scanner is outdated and if PR already exists
         if: ${{ env.release != env.local && env.release != null }}
